main_character = ""
non_friendly = ""
his_age = ""
age_thought = ""
print("There was boy named " + main_character +".")
print("He was inteligent but not in good way,")
print("but in a bad way. He had a ")
print("friend " + non_friendly +"." + main_character + "got")
print("cheated by " + non_friendly +"."+ non_friendly +"shared all")
print("the secrets of " + main_character +".")
print("So, now his not having any friend.")
print("If truth to be said he likes staying alone.")
print("Sometimes students asks 'why are you sitting alone?'")
print("He says 'I like sitting alone'")
print("His class mets also had a misunderstanding in his age.")
print("His actual age was " + his_age +".")
print("But others thought his age is " + age_thought +".")
print(main_character +"tried to say his classmates")
print("that, he is " + his_age +". But no one belives.")
print(main_character +"really likes playing games")
print("       _________              _________")
print("      /         \            /         \ ")
print("     /           \          /           \ ")
print("    /             \        /             \ ")
print("   /               \      /               \ ")
print("  /                 \    /                 \ ")
print(" /                   \  /                   \ ")
print(" \                    \/                    /")
print("  \                                        /")
print("   \                                      /")
print("    \                                    /")
print("     \                                  /")
print("      \                                /")
print("       \                              /")
print("        \                            /")
print("         \                          /")
print("          \                        /")
print("           \                      /")
print("            \                    /")
print("             \                  /")
print("              \                /")
print("               \              /")
print("                \            /")
print("                 \          /")
print("                  \        /")
print("                   \      /")
print("                    \    /")
print("                     \  /")
print("                      \/")
print("                     +__+")
print("I hope my story is good.")